FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ARG ARG_AZURE_API_ENDPOINT
ARG ARG_AZURE_API_KEY
ARG ARG_AZURE_OPENAI_API_ENDPOINT
ARG ARG_AZURE_OPENAI_API_KEY
ARG ARG_PROMPT_PATH
ARG ARG_UPLOAD_PATH

ENV AZURE_API_ENDPOINT=${ARG_AZURE_API_ENDPOINT:-your_azure_form_recognizer_endpoint}
ENV AZURE_API_KEY=${ARG_AZURE_API_KEY:-your_azure_form_recognizer_key}
ENV AZURE_OPENAI_API_ENDPOINT=${ARG_AZURE_OPENAI_API_ENDPOINT:-your_azure_openai_endpoint}
ENV AZURE_OPENAI_API_KEY=${ARG_AZURE_OPENAI_API_KEY:-your_azure_openai_key}
ENV PROMPT_PATH=${ARG_PROMPT_PATH:-path/to/file}
ENV UPLOAD_PATH=${ARG_UPLOAD_PATH:-path/to/file}

EXPOSE 5000

CMD ["python", "app.py"]
