global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']

  - job_name: 'fertiscan-frontend'
    static_configs:
      - targets: ['fertiscan-frontend:3000']

  - job_name: 'fertiscan-backend'
    static_configs:
      - targets: ['fertiscan-backend:5000']