@startuml FertiScan Sequence Diagram
header 10/07/2024

title FertiScan Create Form
hide empty members
hide footbox

participant FertiScan as BE <<http:localhost:5000>>
participant DataStore as DS
database SQL as DB

-> BE: POST /forms
note right BE
  Authorization: Basic
  Content-Type: application/json
  Content: Form
end note
BE -> DS: create_form()
note left
    Creates a new unconfirmed
    form in the backend for the user.
end note
DS -> DB: execute_query()
DS <<-- DB: //SQL_CODE//
BE <<-- DS: //JSON, HTTP_CODE//
alt HTTP_CODE is success
  <<-- BE: //JSON, 200//
  note right
    {
        "message": "...",
        "form_id": "<form_id>"
    }
  end note
else
  <<-- BE: //Database error, HTTP_CODE//
end

@enduml
