@startuml FertiScan Sequence Diagram
header 14/08/2024

title FertiScan Get Inspection
hide empty members
hide footbox

participant FertiScan as BE <<http:localhost:5000>>
participant DataStore as DS
database SQL as DB

-> BE: GET /inspections/<inspection_id>
note right BE
  Authorization: Basic
end note
alt inspection_id is None
  BE -> DS: get_inspections() 
  note right
    This will return all the
    inspections of the user.
  end note
else
  BE -> DS: get_inspection_by_id(inspection_id)
  note right
    This will return the
    inspection with the given
    inspection_id.
  end note
end
DS -> DB: execute_query(query)
DS <<-- DB: //SQL_CODE//
BE <<-- DS: //JSON, HTTP_CODE//
alt HTTP_CODE is success
  <<-- BE: //JSON, 200//
  note right
    A list of inspections that
    match the search query.

    Note: It might not have
    the same format as the one
    returned by the analysis.
  end note
else
  <<-- BE: //message, 500//
  note right
  {
    "error": "...",
  }
  end note
end

@enduml
