@startuml FertiScan Sequence Diagram
header 05/07/2024

title FertiScan Discard Form
hide empty members
hide footbox

participant FertiScan as BE <<http:localhost:5000>>
participant DataStore as DS
database SQL as DB

-> BE: GET /inspections/inspection_id
note right BE
  Authorization: Basic
  Content: Search Query
end note
BE -> DS: get_inspection() 
DS -> DB: execute_query(query)
DS <<-- DB: //SQL_CODE//
BE <<-- DS: //JSON, HTTP_CODE//
alt HTTP_CODE is success
  <<-- BE: //JSON, 200//
  note right
    The inspection as stored in the database.

    Note: It might not have
    the same format as the one
    returned by the analysis.
  end note
else
  <<-- BE: //message, 500//
end

@enduml
