@startuml FertiScan Sequence Diagram
header 10/07/2024

title FertiScan Update Form
hide empty members
hide footbox

participant FertiScan as BE <<http:localhost:5000>>
participant DataStore as DS
database SQL as DB

-> BE: PUT /inspections/inspection_id
note right BE
  Authorization: Basic
  Content: JSON (Form)
end note
alt inspection.confirm == true
  BE -> DS: submit_final_inspection()
  note left
    the final version of 
    the inspection.
  end note
else
  BE -> DS: submit_update_inspection()
  note left
    Update the given inspection.
  end note
end
DS -> DB: execute_query()
DS <<-- DB: //SQL_CODE//
BE <<-- DS: //message, HTTP_CODE//
alt HTTP_CODE is success
  <<-- BE: //message, 200//
else
  <<-- BE: //Database error, HTTP_CODE//
end

@enduml
