@startuml FertiScan Sequence Diagram
header 14/08/2024

title FertiScan Update Inspection
hide empty members
hide footbox

participant FertiScan as BE <<http:localhost:5000>>
participant DataStore as DS
database SQL as DB

-> BE: PUT /inspections/inspection_id
note right BE
  Authorization: Basic
  Content-Type: application/json
  Content: Form
end note
BE -> DS: update_inspection()
note left
  A flag in the JSON will
  indicate if the inspection
  is confirmed or not.
end note
DS -> DB: execute_query()
DS <<-- DB: //SQL_CODE//
BE <<-- DS: //JSON, 500//
alt HTTP_CODE is success
  <<-- BE: //JSON, 200//
  note right
  The inspection form as
  registered in the database.
  end note
else
  <<-- BE: //Database error, HTTP_CODE//
end

@enduml
