@startuml FertiScan Sequence Diagram
header 05/07/2024

title FertiScan Commit Form
hide empty members
hide footbox

actor "Client" as C
participant FertiScan as F <<http:localhost:5000>>
database SQL as DB

C -> F: POST /commit form
note over F
  Commit an object representing
  the form. It can either be
  transient or final.
end note
alt form.confirm == true
  F -> F: query = create_commit_form_final()
  note left
    the final version of 
    the form.
  end note
else
  F -> F: query = create_commit_form_update()
  note left
    Update the given form.
  end note
end
F -> DB: result = execute_query(query)
alt result is success
  C <<-- F: //label_id, 200//
else
  C <<-- F: //Database error, 500//
end

@enduml
