@startuml FertiScan Sequence Diagram
header 05/07/2024

title FertiScan Discard Form
hide empty members
hide footbox

actor "Client" as C
participant Frontend as FE
participant FertiScan as BE <<http:localhost:5000>>
participant DataStore as DS
database SQL as DB

C -> FE: discard_form()
FE -> BE: POST /discard/label_id
note right BE
  The label_id of the
  form you want to discard.
end note
BE -> DS: discard_form() 
DS -> DB: execute_query(query)
DS <<-- DB: //SQL_CODE//
BE <<-- DS: //SQL_CODE, HTTP_CODE//
alt HTTP_CODE is success
  FE <<-- BE: //Successfully discarded, 200//
else
  FE <<-- BE: //Database error, 500//
end

@enduml
