@startuml FertiScan Sequence Diagram
header 05/07/2024

title FertiScan Discard Form
hide empty members
hide footbox

actor "Client" as C
participant FertiScan as F <<http:localhost:5000>>
database SQL as DB

C -> F: POST /discard label_id
note over F
  The label_id of the
  form you want to discard.
end note
F -> F: query = create_discard_query()
F -> DB: result = execute_query(query)
alt result is success
  C <<-- F: //Successfully discarded, 200//
else
  C <<-- F: //Database error, 500//
end

@enduml
