@startuml Model Diagram

header 27-05-2024
 
title FertiScan Domain Model
 
hide empty members
 
class "Flask" as S <<localhost:5000>> {
  + upload_image()
  + analyze_document()
}

class "DocumentStorage" as DS {
+ add_image(image)
+ get_document() Document
}

class "LanguageModel" as LLM {
+ generate_form(prompt)
}

class "OCR" {
+ extract_text(document) AnalyzeResult
}

class "AnalyzeResult" as R
entity "Image" as I
entity "Document" as D
entity "Prompt" as P 
entity "Form" as F
 
 
S "1" -down- "1" OCR: uses >
S "1" -down- "1" LLM: uses >
S "1" -down- "1" DS: uses >
 
OCR "1" -down- "*" R: produces >
DS "1" -down- "*" D: gives > 
DS "1" - "*" I: contains >
LLM "1" -down- "*" P: takes >
LLM "1" -down- "*" F: generates >
R "1" -down- "1" P: contains >

@enduml