@startuml FertiScan Sequence Diagram
header 10/07/2024

title FertiScan Update Form
hide empty members
hide footbox

participant FertiScan as BE <<http:localhost:5000>>
participant DataStore as DS
database SQL as DB

-> BE: PUT /forms/form_id
note right BE
  Authorization: Basic (email as user_id)
  Content: JSON (Form)
end note
alt form.confirm == true
  BE -> DS: submit_final_form()
  note left
    the final version of 
    the form.
  end note
else
  BE -> DS: submit_update_form()
  note left
    Update the given form.
  end note
end
DS -> DB: execute_query()
DS <<-- DB: //SQL_CODE//
BE <<-- DS: //message, HTTP_CODE//
alt HTTP_CODE is success
  <<-- BE: //message, 200//
else
  <<-- BE: //Database error, HTTP_CODE//
end

@enduml
