@startuml Upload DSS
header 22/05/2024

title FertiScan File Upload
hide empty members
hide footbox

actor "Client" as C
participant Frontend as F
participant Backend as B

C -> F: upload()
F -> B: POST /upload "file=@/path/to/file"
alt Document found
F <<-- B: //File uploaded successfully, 200//
else No path givenn
F <<-- B: //No selected file, 400//
else
else Document not found
F <<-- B: //The file does not exist, 400//
end

@enduml
