@startuml FertiScan Sequence Diagram
header 12/06/2024

title FertiScan Workflow
hide empty members
hide footbox

actor "Client" as C
participant FertiScan as F <<http:localhost:5000>>

C -> F: POST /analyze
note over F
  The request takes:
    * 'Basic' authentication token (optional)
    * 'images' of the label
end note
F -> F: analyze()  
C <<-- F: returns JSON
@enduml
