@startuml FertiScan Sequence Diagram
header 07/06/2024

title FertiScan Workflow
hide empty members
hide footbox

actor "Client" as C
participant FertiScan as F <<http:localhost:5000>>

C -> F: GET /new_label
F -> F: new_label()
C <<-- F: returns //label_id//
note right
  All the images will be linked
  to the label with this id.
end note
loop for all images
  C -> F: POST /upload
  F -> F: upload()
  note left
    The request takes the credentials
    in the Authorization header 
    (user_id and token_id).
  end note
end
C -> F: GET /analyze
F -> F: analyze()  
note left    
  This request also takes credentials.
end note
C <<-- F: returns the analysis of the label.
@enduml